### PR TITLE
Immutable store implementation with selectors

### PR DESCRIPTION
**Pull request by jogoodma**
Here is the immutable store implementation with selectors for #5 .  I've synced with dev and resolved all conflicts.  I removed `totalPages` from the store and moved that logic to the `selectTotalPages` selector.  `totalPages` will now only be recalculated if its upstream input of `total` or `pageSize` changes.

### CODE REVIEW

**Comment by ragingsquirrel3** [comment]
Awesome!  I'll have a look at this later today or tomorrow.  I think your logic about `totalPages` makes sense.  Thanks again for bringing your immutable expertise to the project.

**Comment by jogoodma** [comment]
Old comment from the original PR:

> The reducer initializes the immutable store (see fromJS on the DEFAULT_STATE) and uses immutable operations to return new modified copies of state. I did not attempt to deal with the nested object state fields (results, aggregations) and left them as simple key/value fields. This should probably be changed once the structure of the nested objects settles down. The reselect library is used to create performant selectors that populate the container props from the state.

**Comment by ragingsquirrel3** [comment]
Even though the tests pass, I had some runtime errors when I actually ran the application and the client gets an API response. (So one problem is that the tests need to add this scenario).  Were you able to run the application locally?  I know you previously mentioned some python dep issues.

The initial state works, but once there is an API response, these fields get set to plain js objects, rather than immutable objects, which causes an error in the selectors.  I think the issue is with the nested lists.  I was able to solve the problem locally by wrapping the arguments in places like 
https://github.com/FlyBase/agr_prototype/blob/master/src/js_src/reducers/searchReducer.js#L33  with `toJS()`

Does that make sense?  Is there another way to handle that.

**Comment by jogoodma** [comment]
OK, I've got my dev environment up and was able to fix the problem.  I'm using fromJS() to fix it, which works, but it is a bit of a sledgehammer approach.  I'd prefer to use the scalpels that ImmutableJS offers (update, merge, etc.), but that requires a better understanding of how you all envision using the `aggregations` and `results` and their final structure.

**Comment by ragingsquirrel3** [comment]
awesome, works for me, too.  For now, I think the sledgehammer is fine.  The structure of aggs and results is what we use now at sgd, but I'm guessing these things might change and pre optimizing might not make sense.

**Pull request merged**
